# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0003_auto_20161121_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='eje',
            field=models.IntegerField(choices=[(1, b'Gestion de proyectos'), (2, b'Arquitectura de software'), (3, b'Desarrollo de software'), (4, b'Comunicacion en ingles'), (5, b'Educacion general'), (6, b'Vinculacion con el medio')]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.IntegerField(choices=[(1, b'Desarrollo'), (2, b'Seleccion multiple'), (3, b'Terminos pareados')], default=1),
        ),
    ]
