# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0004_auto_20161121_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='objetivos',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sec.asignatura'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sec.asignatura'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sec.asignatura'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='contenido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sec.contenido'),
        ),
    ]
