# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0005_auto_20161122_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='cant_preguntas',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas',
            field=models.ManyToManyField(to='sec.pregunta'),
        ),
    ]
