# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0006_auto_20161122_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='preguntas',
            field=models.ManyToManyField(blank=True, null=True, to='sec.pregunta'),
        ),
    ]
