# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0013_auto_20161123_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
